basePath: /api
host: short.sidesideeffect.io
info:
  contact:
    email: nocvi111@gmail.com
    name: sidesideeffect.io
    url: https://github.com/shlason/url-shortener
  description: This is a sample server celler server.
  license:
    name: MIT
    url: https://github.com/shlason/url-shortener/blob/main/LICENSE
  title: URL-Shortener Example API
  version: "1.0"
paths: {}
swagger: "2.0"
